[package]
name = "ods-rust"
version = "0.1.0"
authors = ["Yusuke Tanaka <wing0920@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]

[workspace]
members = [
    "chapters/01_introduction",
    "chapters/02_array_list"
]
